### ISSUE TITLE
Не точная длительность видео

### ISSUE THREAD

**Issue by Mintedan** [cawa-93/anime-library#21]
### Важная информация

- **Версия приложения**: 21.6.1 и предыдущая
- **Версия OS**: Windows 10

### Описание

Все видео больше часа не отображают реальную длительность ну точнее не показываются только часы 
![Безый](https://user-images.githubusercontent.com/84447208/120358570-4d13c880-c30f-11eb-8716-835ae38b02a7.png)
 

### Как воспроизвести

Опишите пошагово как воспроизвести ошибку. Например:

1. Откройте '...'
2. Нажмите на '...'
3. Увидите ошибку '...'

**Comment by cawa-93** [comment]
Спасибо за репорт :)
