### ISSUE TITLE
Не загружается серия

### ISSUE THREAD

**Issue by Mintedan** [cawa-93/anime-library#83]
### Важная информация

- **Версия приложения**: 21.7.5-664 и предыдущая
- **Версия OS**: Windows 10

### Описание

4 серия почему то не появляется на сайте открывается нормально. возможно связано с тем что патается открыть в 1080p смотри следующий баг

### Как воспроизвести

Опишите пошагово как воспроизвести ошибку. Например:

1. Откройте https://shikimori.one/animes/z37450-seishun-buta-yarou-wa-bunny-girl-senpai-no-yume-wo-minai
2. Нажмите на 4 серию
3. Увидите ошибку бесконечная загрузка

**Comment by cawa-93** [comment]
Спасибо за сообщение. Видел что встречается такая проблема, но не мог отловить причину.

**Comment by Mintedan** [comment]
ну у меня эта проблема повторилась и в версии 21.7.5-1128 но потом я полностью удалил и установил заново вроде те серии что не работали заработали
