### ISSUE TITLE
Фризы на 1080p

### ISSUE THREAD

**Issue by Mintedan** [cawa-93/anime-library#84]
### Важная информация

- **Версия приложения**: 21.7.5-664 и предыдущая
- **Версия OS**: Windows 10

### Описание

Видео в 1080 в начале некоторое время тормозит на сайте работает нормально 

### Как воспроизвести

Опишите пошагово как воспроизвести ошибку. Например:

1. Откройте https://shikimori.one/animes/z37450-seishun-buta-yarou-wa-bunny-girl-senpai-no-yume-wo-minai
2. Нажмите на любую серию в 1080
3. Увидите ошибку https://youtu.be/vziPsT7h2hs

**Comment by cawa-93** [comment]
Даже не представляю с чем это может быть связано. Тормозит только это аниме или вообще любое?

**Comment by Mintedan** [comment]
проверил еще 2 аниме тоже какие то лаги в начале но только в разрешении 1080
самое интересное звук не прерывается 
хотя возможно проблемы у меня с интернетом потому что иногда когда начинает подвисать на секунду появляется круг загрузки но на самом сайте такой проблемы нет

**Comment by cawa-93** [comment]
Опишите характеристика вашего устройства и ОС

**Comment by Mintedan** [comment]
Информация о компьютере:
    Производитель: MSI
    Модель: MS-7982
    Тип: Настольный
    Сенсорный ввод не поддерживается

Процессор:
    Производитель процессора: GenuineIntel
    Производитель процессора: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
Версия ОС:
    Windows 10 (64 бит)
    NTFS:  Поддерживается
    Коды Crypto Provider: Поддерживается 311 0x0 0x0 0x0

Видеокарта:
    Модель:  NVIDIA GeForce GTX 1050 Ti
    Драйвер DirectX:  nvldumd.dll
    Версия драйвера:  30.0.14.7111
    Версия драйвера DirectX:  30.0.14.7111
    Дата выхода: 6 21 2021
    Версия OpenGL: 4.6
    Глубина цвета: 32 бит/пиксель
    Частота обновления: 74 Гц

Звуковая карта:
    Аудиоустройство: Динамики (Realtek(R) Audio)

Память:
    Оперативная память:  16348 МБ
ну и ссд и шдд
программа на ссд
Ну это из стима

**Comment by cawa-93** [comment]
Попробуйте эти эксперименты https://1drv.ms/u/s!AvZrbaLzAPjrgv1a94sdCxt5UYibsA?e=hhRECm

**Comment by Mintedan** [comment]
все работают и не тормозят

**Comment by cawa-93** [comment]
@Mintedan Попробуйте пожалуйста эти два эксперимента:
https://1drv.ms/u/s!AvZrbaLzAPjrgv1dlJKSCZtVHmSOAw?e=H9fXzf

Скажите в какой версии есть лаги? Кроме этого, в консоль (отладчик можно открыть клавишами `Crtl+Shift+I`) добавил отладочную информацию, не могли бы вы её прислать. Там будет что-то в таком роде:
![зображення](https://user-images.githubusercontent.com/1662812/124717418-c5246e00-df0d-11eb-8c40-72e900aca983.png)

**Comment by Mintedan** [comment]
anime-library-soft-acceleration лагает
![anime-library-soft-acceleration](https://user-images.githubusercontent.com/84447208/124793307-87980300-df56-11eb-8d78-978c8eb9c182.png)

anime-library-hard-acceleration не лагает
![anime-library-hard-acceleration1](https://user-images.githubusercontent.com/84447208/124793275-7e0e9b00-df56-11eb-8e7a-45b8ee4ecbd3.png)
